version: '2'

services:
  n3uron:
    build: .
    ports:
      - "80:8003"
    environment:
      - HOSTNAME=balena01
    volumes:
      - config:/opt/n3uron/config
      - data:/opt/n3uron/data
      - licenses:/opt/n3uron/licenses
      - log:/opt/n3uron/log
    cap_add:
      - SYS_ADMIN
    restart: always

volumes:
  config:
  data:
  licenses:
  log:
