version: '2'

services:
  n3uron:
    build: .
    ports:
      - 8003:8003 # HTTP WebUI
      - 8443:8443 # HTTPS WebUI
      - 8004:8004 # HTTP WebVision
      - 8444:8444 # HTTPS WebVision
      - 3001:3001 # Inbound Links
    environment:
      - HOSTNAME=balena01
    volumes:
      - config:/opt/n3uron/config
      - data:/opt/n3uron/data
      - licenses:/opt/n3uron/licenses
      - log:/opt/n3uron/log
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    restart: always

volumes:
  config:
  data:
  licenses:
  log:
